version: 2.1

orbs:
   win: circleci/windows@2.4.0

workflows:
  build-and-test-all:
    jobs:
      - build-test-linux:
          name: latest Node version
          docker-image: cimg/node:current
          run-lint: true
      - build-test-linux:
          name: Node 16
          docker-image: cimg/node:16
          run-lint: false
      - build-test-linux:
          name: Node 15
          docker-image: cimg/node:15
          run-lint: false
      - build-test-linux:
          name: Node 14
          docker-image: cimg/node:14
          run-lint: false
      - build-test-linux:
          name: Node 13
          docker-image: cimg/node:13
          run-lint: false
      - build-test-linux:
          name: Node 12
          docker-image: cimg/node:12
          run-lint: false
      - build-test-linux:
          name: Node 11
          docker-image: cimg/node:11
          run-lint: false
      - build-test-linux:
          name: Node 10
          docker-image: cimg/node:10
          run-lint: false
      - build-test-linux:
          name: Node 9
          docker-image: cimg/node:9
          run-lint: false
      - build-test-linux:
          name: Node 8
          docker-image: cimg/node:8
          run-lint: false
      - build-test-linux:
          name: Node 6
          docker-image: circleci/node:6
          run-lint: false
      - build-test-windows:
          name: Windows

jobs:
  build-test-linux:
    parameters:
      run-lint:
        type: boolean
      docker-image:
        type: string
    docker:
      - image: <<parameters.docker-image>>
      - image: redis
    steps:
      - checkout
      - run: echo "Node version:" `node --version`
      - run: npm install
      - run:
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run: npm run check-typescript
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: npm run lint
      - run:
          name: dependency audit
          command: ./scripts/better-audit.sh
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  build-test-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: set up Redis
          command: |
            $ProgressPreference = "SilentlyContinue"  # prevents console errors from CircleCI host
            iwr -outf redis.zip https://github.com/MicrosoftArchive/redis/releases/download/win-3.0.504/Redis-x64-3.0.504.zip
            mkdir redis
            Expand-Archive -Path redis.zip -DestinationPath redis
      - run:
          name: start Redis
          command: |
            cd redis
            ./redis-server --service-install
            ./redis-server --service-start
            Start-Sleep -s 5
            ./redis-cli ping
      - run: node --version
      - run: npm install
      - run: npm test
