repo:
  public: node-server-sdk
  private: node-server-sdk-private

publications:
  - url: https://www.npmjs.com/package/launchdarkly-node-server-sdk
    description: npm

template:
  name: npm

documentation:
  githubPages: true
  title: LaunchDarkly Server-Side Node SDK

sdk:
  displayName: "Node"
